.\" Automation of MitM Attack on WiFi Networks
.\" Bachelor's Thesis UIFS FIT VUT
.\" Martin Vondracek
.\" 2016


.TH WIFIMITMCLI 1 "2016-05-18" "version 0.6.0" "Wi-Fi Machine-in-the-Middle"


.nh


.SH NAME
wifimitmcli \- Wi-Fi Machine-in-the-Middle command-line interface


.SH SYNOPSIS
.B wifimictmcli
.RB [\| \-h \|]
.RB [\| \-v \|]
.RB [\| \-ll
.IR <level> \|]
.RB [\| \-p \|]
.RB [\| \-cf
.IR FILE \|]
.I <essid>
.I <interface>


.SH DESCRIPTION
The 
.B wifimitmcli
tool is capable of performing a fully automated Man-in-the-Middle attack
on wireless networks without any intervention from an attacking person.
It can be used for automated penetration testing and for forensic investigation.

During its run, usual output information is written to
.IR stdout ", notifications concerning errors are written to"
.IR stderr "."
.B  Wifimitmcli
saves and loads attack data from the
.IR "~/.wifimitm/" " directory." 



.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help message and exit.
.TP
.BR \-v ", " \-\-version
Show program's version number and exit.
.TP
.BI \-ll " <level>" \fR,\ \fB\-\-logging\-level " <level>"
Select logging level (choices:
.BR disabled ", " critical ", " error ", " warning ", " info ", " debug ")."
.TP
.BR \-p ", " \-\-phishing
Enable phishing attack if dictionary attack fails.
.TP
.BI \-cf " FILE" \fR,\ \fB\-\-capture\-file " FILE"
Capture network traffic to provided file.
.TP
.I <essid>
Attack network with provided ESSID.
.TP
.I <interface>
Use provided wireless network interface for attack.


.SH "EXIT STATUS"
.TP
.B 0
Program terminated successfully.
.TP
.B 2
Incorrect or missing arguments provided.
.TP
.B 69
Required program or file does not exist.
.TP
.B 77
Permission denied.
.TP
.B 79
Target AP was not found during scan.
.TP
.B 80
WPA/WPA2 passphrase was not found in any available dictionary.
.TP
.B 81
WPA/WPA2 passphrase obtained from phishing attack is incorrect.
.TP
.B 82
Failure in subprocess occured.
.TP
.B 130
Program received SIGINT.


.SH FILES
.I ~/.wifimitm/
.RS
Various attacks executed against the selected AP require some information to be captured
first. ARP request replay attack on WEP secured networks requires an
.I "ARP request"
to be captured in order to start an attacking procedure. Fake authentication in WEP SKA
secured network requires
.I "PRGA XOR"
obtained from a detected authentication. Dictionary attack against WPA PSK and WPA2 PSK
secured networks requires a captured
.IR handshake "."
Finally, for successful connection to a network, a correct
.I key
is required.

When the required information is obtained, it can be saved for a later usage to speed up
following or repetitive attacks. These data are implicitly stored as files inside user's home
directory in
.I .wifimitm/
directory. Data from successful attacks could be even shared
between users of the implemented tool.
.RE


.SH COPYRIGHT
Copyright (c) 2016 Martin Vondracek, The MIT License (MIT)

.SH REFERENCE
VONDRÁČEK, Martin.
.IR "Automation of MitM Attack on WiFi Networks" "."
Brno, 2016. Bachelor's thesis. Brno University of Technology, Faculty of Information Technology.
Supervisor Pluskal Jan, Briffa Johann.
