@startuml
title WEP attack
header
**Automatization of MitM Attack on WiFi Networks**
Bachelor's Thesis UIFS FIT VUT
Martin Vondracek
2016
end header
legend
simplified version
end legend

start

if (Already cracked?) then (no)


    :**start** Capture IV]
    :**start** Fake Authentication]
    note
        Sends keep-alive packets.
        Can use previously saved
        PRGA XOR, if available.
    end note
    if (Needs to capture PRGA XOR?) then (yes)
        note
        PRGA XOR is needed for
        Shared Key Authentication.
        end note

        :Repeatedly deauthenticate
        stations one by one, until
        PRGA XOR is captured.;
    else (no)
    endif

    :**start** ARP Replay]
    note
        Uses previously saved
        ARP capture, if available.
        If ARP capture is not
        available, it is saved after
        detection of ARP Request.
    end note

    :**start** WEP PSK Crack]

    while (Cracked?) is (no)
        :check feedbacks;
        :wait;
    end while (yes)

    :**stop** all]
else (yes)
endif
stop
@enduml