@startuml
title MitM
header
**Automatization of MitM Attack on WiFi Networks**
Bachelor's Thesis UIFS FIT VUT
Martin Vondracek
2016
end header
legend
simplified version
end legend

start

#Grey:select wireless interface/


:Scan networks;
:Update known;
note: already attacked networks
:Choose AP for attack/

if (OPEN) then (yes)
    if (Eavesdrop disconnected?) then (yes)
        #Grey:Eavesdrop in monitor mode;
        stop
    else (no)
        :Connect;
        #Grey:Default gateway spoofing;
    endif
elseif (WEP) then (yes)
    :WEP attack|
    if (Eavesdrop disconnected?) then (yes)
        #Grey:Eavesdrop in monitor mode;
        #Grey:Decrypt with WEP PSK;
        stop
    else (no)
        :Connect;
        #Grey:Default gateway spoofing;
    endif
elseif (WPA or WPA2) then (yes)

    if (Crack?) then (yes)
        :WPA2 attack|
        :Connect;
        #Grey:Default gateway spoofing;
    elseif (Impersonate?) then (yes)
        #Grey:Impersonate;
    else (no)
        end
    endif
else
    end
endif

#Grey:Capture;

stop
@enduml