@startuml
title WPA2 attack
header
**Automation of MitM Attack on WiFi Networks**
Bachelor's Thesis UIFS FIT VUT
Martin Vondracek
2016
end header
legend
simplified version
end legend

start

if (Already cracked?) then (no)
    if (Needs to capture handshake?) then (yes)
        :**start** Capture]

        :Repeatedly deauthenticate
        stations one by one, until
        handshake is captured.;

        :save handshake;
    else (no)
    endif

    partition "Personalize dictionary"{
        split
            #Grey:upc_keys UPC%07d;
        split again
        end split
    }

    :**start** WPA PSK Dictionary attack]

    while (Cracked?) is (no)
        :check feedback;
        :wait;
    end while (yes)

else (yes)
endif
stop
@enduml